# Author    : Cristian Troncoso 

CC=g++
CCFLAGS= -g -O0 -std=c++11 -Wall
INCLUDE =./

LIBS = 

BMHEXE = grid

$(BMHEXE):./grid.cpp
	$(CC) $^ $(CCFLAGS) $(LIBS) -I $(INCLUDE) -o $@


clean:
	rm -f grid

